name = "attila-reviews"
compatibility_date = "2026-04-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "reviews-db"
database_id = "0ac66939-6008-4ff5-9e74-8f22b90c5689"
